wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1653777571
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      4: 3.9.7
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 32
checkpoints_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/checkpoints/z_axis/factor_2/
config:
  desc: null
  value: yaml/srdense_exp1.yaml
criterion:
  desc: null
  value: mse
dataset_name:
  desc: null
  value: z_axis
dataset_size:
  desc: null
  value: resolution_dataset50
device:
  desc: null
  value: cuda
epoch_image_path:
  desc: null
  value: resolution_dataset50/z_axis/factor_2/train/lr_f1_160_2_z_46.png
epoch_images_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/epoch_images/z_axis/factor_2/
exp_name:
  desc: null
  value: srdense_test
factor:
  desc: null
  value: 2
grad_norm_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/grad_norm/z_axis/factor_2/
growth_rate:
  desc: null
  value: 7
input_images_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/input_images/z_axis/factor_2/
loss_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/losses/z_axis/factor_2/
lr:
  desc: null
  value: 0.0001
model_name:
  desc: null
  value: srdense
n_freq:
  desc: null
  value: 5
num_blocks:
  desc: null
  value: 5
num_epochs:
  desc: null
  value: 20
num_layers:
  desc: null
  value: 5
num_workers:
  desc: null
  value: 8
optimizer:
  desc: null
  value: adam
output_images_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/output_images/z_axis/factor_2/
patch:
  desc: null
  value: false
plot_dir:
  desc: null
  value: outputs/resolution_dataset50/srdense/srdense_test/plots/z_axis/factor_2/
project_name:
  desc: null
  value: super_resolution
scale:
  desc: null
  value: 4
seed:
  desc: null
  value: 123
train_batch_size:
  desc: null
  value: 32
train_image_dir:
  desc: null
  value: resolution_dataset50/z_axis/factor_2/train
train_label_dir:
  desc: null
  value: resolution_dataset50/z_axis/label/train
val_batch_size:
  desc: null
  value: 1
val_image_dir:
  desc: null
  value: resolution_dataset50/z_axis/factor_2/val
val_label_dir:
  desc: null
  value: resolution_dataset50/z_axis/label/val
wandb:
  desc: null
  value: true
weights_file:
  desc: null
  value: None
