#configuration file
#this is file for training patch_gan with unet as generator

model_name: 'patch_gan'
exp_name: 'patch_gan_unet'
generator_type: 'unet'  #options: unet, unet_small, dense, resunet
dataset_size: resolution_dataset50
dataset_name: 'z_axis'
num_epochs: 500
num_workers: 8
seed: 123
lr: 0.0001
n_freq: 100
train_batch_size: 32
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 2
wandb: True 
project_name: 'super_resolution'


#gan unet
n_blocks: 4
start_filters: 32
activation: 'relu'
normalization: 'batch'
conv_mode: 'same'
dim: 2
up_mode: 'transposed'
init: 'kaiming'  #options: norm,xavier,kaiming
weights_file: None
patch: False
tensorboard: False
gan_mode: 'lsgan'  # options: vanilla, lsgan


#learning rate
lr_G: 0.0001
lr_D: 0.0001
lambda_L1: 100


#patch discriminator
n_down: 3
num_filters: 64