#configuration file
#this is file for training srdense net with original training type

model_name: 'rrdbnet'
exp_name: 'RRDBNET_NB5_KAI_NE605_BS32_LR0.001_P96_F2_ADAM_MSE_ltypeOrig'
training_type: 'original'
edge_type: 'downsample'  #options: canny, downsample. if downsample provide opt.downsample_train_dir and opt.downsample_val_dir also
loss_type: 'original'  #options addition, original:
 #for addition mse is calculate after adding edges and loss calculated between (image and label image) else loss cal between edges
project_name: 'super_resolution'
wandb: True 
dataset_size: resolution_dataset50
size: 50
dataset_name: 'patch'
num_epochs: 605
num_workers: 8
seed: 123
lr: 0.0001
n_freq: 100 # model checkpoint saving frequency
train_batch_size: 64
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 2
lr_decay_factor: 0.9
# init: 'kaiming'  #options: norm,xavier,kaiming

#srdense
criterion: mse
optimizer: adam
# momentum: 
# weight_decay:
num_blocks: 5
patch: True
patch_size: 96

note: 'training rrdbnet for patch size 96 with original loss (calculated in edges) on downsample edges'