#configuration file
#this is file for training srdense net with original training type


model_name: 'rrdbnet'
exp_name: 'rrdbnet_hanning_dataset25'
training_type: 'original'
project_name: 'super_resolution'
wandb: True 

dataset_size: dataset_images/hanning_dataset25

dataset_name: 'z_axis'
size: 25

dir_dict: 'dataset_images/hanning_dataset25/annotation_train_dict_full_path.pkl'
# val_dir_dict: 'dataset_images/hamming_dataset25/annotation_val_dict.pkl'
num_epochs: 505
num_workers: 4
seed: 547
lr: 0.0001
original_lr: 0.0001
lr_decay_factor: 0.95

n_freq: 50 # model checkpoint saving frequency
train_batch_size: 4
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 2
init: 'norm' 
addition: False
# init: 'kaiming'  #options: norm,xavier,kaiming


#rrdbnet
criterion: mse
optimizer: adam
weights_file: None
num_blocks: 7


patch: False



