#configuration file
#this is file for training srdense net with original training type


model_name: 'srdense'
# exp_name: 'srdense_norm_init'
exp_name: 'SRDENSE_GR7NB5NL5S4_KAI_NE3005_BS32_LR0.006_Z_F4_ADAM_MSE'
training_type: 'original'
project_name: 'super_resolution'
wandb: True 
dataset_size: resolution_dataset50
dataset_name: 'z_axis'
num_epochs: 3005
num_workers: 8
seed: 12ddd3
lr: 0.006
n_freq: 100 # model checkpoint saving frequency
train_batch_size: 32
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 4
# init: 'norm' 
init: 'kaiming'  #options: norm,xavier,kaiming

#srdense
criterion: mse
optimizer: adam
growth_rate: 7
num_blocks: 5
num_layers: 5
weights_file: None
scale: 4
patch: False



