#configuration file
#this is file for training srdense net with original training type


model_name: 'srdense'
exp_name: 'SRDENSE_EDGES_DEBUG'
# exp_name: 'srdense_kaiming_init'
training_type: 'original'
loss_type: 'original'  #options addition, original:
 #for addition mse is calculate after adding edges and loss calculated between (image and label image) else loss cal between edges
project_name: 'super_resolution'
wandb: True 
dataset_size: resolution_dataset50
size: 50
dataset_name: 'z_axis'
num_epochs: 16
num_workers: 8
seed: 123
lr: 0.01
n_freq: 2 # model checkpoint saving frequency
train_batch_size: 32
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 4
init: 'norm' 
# init: 'kaiming'  #options: norm,xavier,kaiming

#srdense
criterion: mse
optimizer: adam
# momentum: 
# weight_decay:
growth_rate: 7
num_blocks: 5
num_layers: 5
weights_file: None
scale: 4
patch: False

note: 'this is trained after making correction of last layer as tanh instead of conv and replacing relu with leaky_relu with negative slope of 0.1'

