#configuration file
#this is file for training srdense net with original training type

model_name: 'srdense'
# exp_name: 'srdense_norm_init'
exp_name: '3DSRDENSE_GR7NB5NL5S4_KAI_NE805_BS16_LR0.001_Z_F2_ADAM_MSE'
training_type: 'original'
project_name: 'super_resolution'
wandb: True 
dataset_size: '3d_dataset_50'
num_epochs: 805
num_workers: 8
seed: 123
lr: 0.001
patch_size: 64
n_freq: 100 # model checkpoint saving frequency
train_batch_size: 16
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 2
# init: 'norm' 
init: 'kaiming'  #options: norm,xavier,kaiming
addition: False

#srdense
criterion: mse
optimizer: adam
growth_rate: 7
num_blocks: 5
num_layers: 5
weights_file: None
scale: 4
patch: False



