#configuration file
#this is file for training srdense net 

#task remaining
#srgan training
# eval for models
#visualization 
#wb visualize
# resuming training setup

model_name: 'unet'
exp_name: 'unet_exp'
training_type: 'original'
project_name: 'super_resolution'
wandb: True 
dataset_size: resolution_dataset50
dataset_name: 'z_axis'
num_epochs: 800
num_workers: 8
seed: 123
lr: 0.0001
n_freq: 100
batch_size: 32
train_batch_size: 32
val_batch_size: 1   #set the val batch size to 1 always as we need to claculate the psnr and ssim
# opt.device: cpu or gpu during training
factor: 2


criterion: mse
optimizer: adam

#unet
n_blocks: 4
start_filters: 32
activation: 'relu'
normalization: 'batch'
conv_mode: 'same'
dim: 2
up_mode: 'transposed'
init: 'kaiming'
weights_file: None
patch: False
